Installing Neccessary libraries

In [1]:
!pip install requests sqlalchemy beautifulsoup4 python-dotenv psycopg2

Requirement already satisfied: requests in c:\users\dell\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: sqlalchemy in c:\users\dell\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: beautifulsoup4 in c:\users\dell\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: python-dotenv in c:\users\dell\anaconda3\lib\site-packages (0.21.0)
Requirement already satisfied: psycopg2 in c:\users\dell\anaconda3\lib\site-packages (2.9.10)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\anaconda3\lib\site-packages (from requests) (2024.8.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\dell\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)

Importing the libraries

In [2]:
from sqlalchemy import create_engine, text
from bs4 import BeautifulSoup
import pandas as pd
import requests
from dotenv import load_dotenv
import os 
import re

In [3]:
from sqlalchemy import create_engine, text

Test the Response Status

In [4]:
url = 'https://www.ebay.co.uk/'
response = requests.get(url)
response

In [5]:
response.text

'<!--vertlandweb#s0-1-0--><!DOCTYPE html><!--[if IE 9 ]>    <html class="ie9"> <![endif]--><!--[if (gt IE 9)|!(IE)]><!--><html lang=en><!--<![endif]--><head><!--vertlandweb^s0-1-0-4 s0-1-0 4--><!--vertlandweb/--><!--vertlandweb^s0-1-0-5 s0-1-0 5--><link rel="dns-prefetch" href="//ir.ebaystatic.com"><link rel="dns-prefetch" href="//secureir.ebaystatic.com"><link rel="dns-prefetch" href="//i.ebayimg.com"><link rel="dns-prefetch" href="//rover.ebay.com"><script>$ssgST=new Date().getTime();</script><!--vertlandweb/--><link rel=preload as=image href=https://ir.ebaystatic.com/pictures/aw/pics/s_1x2.gif crossorigin><meta charset=utf-8><link rel=icon href=https://pages.ebay.com/favicon.ico><meta name=viewport content="width=device-width, initial-scale=1, user-scalable=yes, minimum-scale=1"><meta http-equiv=X-UA-Compatible content=IE=edge><link href=https://srv.uk.ebayrtm.com rel=preconnect><noscript><style>\n        .js-only {\n          display: none !important;\n        }\n      </style></noscript><script>\n      window.layoutStart = Date.now();\n      window.vertlandweb = {"isWebpSupported":false,"isLowBandwidth":false,"lazyLoadAll":true,"showSpeedInConsole":false,"isMobileLayout":false};\n      // We need a way to pass the global config setting for enabling/disabling cookie-observer\n      // inline script. Hence we get it from our global config and attach it to the window object.\n      // So that the inline script injected as a part of include-html tag below has access to it.\n      window.ENABLE_VLP_COOKIE_OBSERVER = false;\n    </script><script type="text/javascript" data-type="inline_js">(()=>{var e={138:e=>{"use strict";var t=/(?:\\d*\\.)?\\d+/g,n=[64,96,140,200,225,300,400,500,640,960,1200,1600],o={containsThumbs:function(e){return e.indexOf("thumbs")>-1},isZoomUrl:function(e){var t=this.containsThumbs(e)?8:7;return!(e.length!==t||!e[e.length-1].match("s-l"))||(console.debug("This image url is not valid Zoom format: ".concat(e.join("/"))),!1)},getParts:function(e,t){return e.split(t)},replaceType:function(e,t,n){var o=e,a=n?7:6,i=t.type||!t.cachedPage&&t.webp&&"webp";if(i){var r=this.getParts(o[a],".");r[1]=i,o[a]=r.join(".")}return o},getNearestSize:function(e){var t;for(t=0;t<n.length-1;t++)if(n[t]>=e)return n[t];return n[t]},getConnection:function(){return"undefined"!=typeof navigator&&navigator.connection&&navigator.connection.effectiveType},isLowBandwidth:function(e){var t=this.getConnection();return t?["slow-2g","2g","3g"].filter((function(e){return e===t})).length:!e.cachedPage&&e.lowBandwidth},replaceSize:function(e,n,o){var a,i=e,r=o?7:6;a=n.size?n.size:i[r].match(t)[0],window.innerWidth<a&&n.safeSizeImages&&(a=this.getNearestSize(window.innerWidth));var d=window.devicePixelRatio||1;return!n.disableHDSizing&&d>1&&!n.lowBandwidth&&(n.disable3xSizing?a*=2:a*=d),i[r]=i[r].replace(t,this.getNearestSize(a)),i},transformUrl:function(e){var t=this.getParts(e.src,"/"),n=this.containsThumbs(t);return this.isZoomUrl(t)?(t=this.replaceSize(t,e,n),(t=this.replaceType(t,e,n)).join("/")):e.src}};e.exports=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};return e.lowBandwidth=o.isLowBandwidth(e),function(t,n,a){try{var i=Object.create(e);return i.src=t,n&&(i.size=n),a&&(i.type=a),o.transformUrl(i)}catch(e){return console.debug("There was an error trying to transform this zoom url: ".concat(t,", size: ").concat(n,", type: ").concat(a,", ").concat(e.stack)),t}}},e.exports.helpers=o},519:e=>{e.exports=(e,t,n)=>{if(!e)return!1;const o=n||0,a=window.innerHeight,i=t||window.innerWidth,r=e.getBoundingClientRect(),d=r.top<=a+o&&r.top+r.height>=0,s=r.left<i&&r.left+r.width>0;return d&&s}},816:(e,t,n)=>{const o=n(519),a=n(138),i="load",r="error",d="lazyLoad",s="lazyLoadSwap",l="addEventListener",c="removeEventListener",u="removeAttribute",m="hasAttribute",g="data-load-time",p="setAttribute",w="getAttribute",h="getElementsByClassName",f="querySelectorAll",v="data-vl-atf",y=window.performance&&window.performance.timing,I=Array.prototype.slice,b=e=>parseInt(e[w](g)),L=e=>{const t=Date.now();return e[p](g,t),t},T="data-m-atf",E="vl-atf-module-js",S={hasSpeedMetricsReported:!1,queue:[],swapQueue:[],atfImageList:[],mainContentRect:{},startTime:"undefined"==typeof $ssgST?Date.now():$ssgST,init(){window.lazyLoadInit=Date.now(),S.zoomClient=a({webp:window.vertlandweb.isWebpSupported,lowBandwidth:window.vertlandweb.isLowBandwidth,cachedPage:!1,disableHDSizing:!window.vertlandweb.isMobileLayout}),window.lazyLoad=window.lazyLoad||{},window.lazyLoad.addToQueue=(e,t)=>{if(e[u]("onerror"),e[u]("onload"),"{}"===JSON.stringify(S.mainContentRect)&&(S.mainContentRect=S.getMainContentRect()),0===S.atfImageList.length&&(S.atfImageList=S.buildATFImageList()),e[m]("data-load-immediately"))return t?S.loadImageDiv({target:e.parentElement}):S.loadImage({target:e});if(S.shouldLoadImageInHighPriority(e))return S.loadImageInHighPriority(e,t);if(t){const t=e.parentElement;t[l](d,S.loadImageDiv),S.queue.unshift(t),S.loadImageIfVisible({image:t,immediate:e})}else e[l](d,S.loadImage),S.queue.unshift(e),S.loadImageIfVisible({image:e,immediate:e})},window[l](i,S.loadAll),window.tempLazyLoadQueue&&(window.tempLazyLoadQueue.forEach((e=>{let{el:t,fit:n}=e;window.lazyLoad.addToQueue(t,n)})),window.tempLazyLoadQueue=[]),window[l](i,S.reportATFTimeFromPageLoad)},tearDown(){window[c](i,S.loadAll),window[c](i,S.reportATFTimeFromPageLoad)},buildATFImageList:()=>I.call(document[h](E),0,2).reduce(((e,t)=>e.concat(I.call(t[h]("vl-image-js")))),[]),reportATFTimeFromPageLoad(){S.setOKToReport(!0),S.reportATFTime()},reportATFTime(){const e=S.getATFMetrics(!0);S.showSpeedInConsole(e),delete e.lastImageLoaded,S.hasSpeedMetricsReported=!0;const t=new Event("site-speed-ebay.metricsData");t.detail=e,document.dispatchEvent(t)},getModuleATFMetrics(){const e=Array.from(document[h](E)).slice(0,3);let t="";return e.map((e=>{const n=Array.from(e[f](`[${v}]`)),o=n.length||0;e.setAttribute("data-m-size",o);const a=n.sort(((e,t)=>b(t)-b(e)))[0];a&&(e.setAttribute(T,y?b(a)-y.responseStart:0),t+=`${e[w]("data-m-id")}:${e[w](T)}:${o}|`)})),t},getATFMetrics(){const e={},t=S.getATFLoadedImages(),n=t.sort(((e,t)=>b(t)-b(e))),o=n[0],a=n[n.length-1],i=o?b(o):Date.now(),r=a?b(a):Date.now();return e.jsljgr2=i-S.startTime,y&&(e.i_29i=i-y.responseStart),y&&(e.i_1i=r-y.responseStart),e.i_0i=t.length,e.lastImageLoaded=o,e.atfdtls=o?S.getModuleATFMetrics():null,window.vlServiceTime>0&&(e.i_2i=window.vlServiceTime),e},getATFLoadedImages(){const e=I.call(document[h](E),0,2).reduce(((e,t)=>e.concat(I.call(t[f](`[${v}]`)))),[]),t=e.filter((e=>e[m](g)&&!e[m]("exclude-from-high-fetchpriority")));return window.vertlandweb.showSpeedInConsole&&console.log("Lazyload Init() getATFLoadedImages() loadedImageList",t),e.length===t.length&&S.setOKToReport(!1),t},setOKToReport(e){S.oKToReport=e},showSpeedInConsole(e){window.vertlandweb.showSpeedInConsole&&console.log("Speed data:",Object.assign({},e))},getSrc(e){const t=e.dataset;return S.zoomClient(t.src,parseInt(t.size,10))},loadImage(e){const t=e.target,n=t.dataset;let o=S.getSrc(t);e.fetchpriority&&t[p]("fetchpriority",e.fetchpriority),"true"!==n.itemCard||n.vlAtf||window.vertlandweb.isMobileLayout||(o=S.zoomClient(n.src,parseInt(n.highResSize,10))),t[l](i,S.imageLoadHandler),t[l](r,S.imageLoadErrorHandler),t.src=o},addToSwapQueue(e){e[l](s,S.loadSwapImage),S.swapQueue.push(e)},loadSwapImage(e){const t=e.target,n=t.dataset,o=S.zoomClient(n.src,parseInt(n.highResSize,10)),a=new Image;a.src=o,a.onload=()=>{t.src=o,t[c](s,S.loadSwapImage)}},imageLoadHandler(e){const t=e.target;t&&(L(t),t[c](i,S.imageLoadHandler),t[c](r,S.imageLoadErrorHandler),t.style.opacity=1)},imageLoadErrorHandler(e){const t=e.target;t&&(L(t),t[c](d,S.loadImage),t.style.opacity=0,S.reportError(t))},loadImageDiv(e){const t=e.target,n=S.getSrc(t);if(!n)return void console.error("Can\'t find source of image",t);let o=t.children[1];e.fetchpriority&&o[p]("fetchpriority",e.fetchpriority);const a=function(){t&&o&&(L(o),t.removeChild(o),o=null,t[c](d,S.loadImage),t.style.backgroundImage="none",t.children[0].style.opacity=1,S.reportError(t))},s=function(){t&&o&&(L(o),o.src=n,o[c](i,s),o[c](r,a),t.style.backgroundImage=`url(\'${n}\')`,t.children[0].style.opacity=0)};o[l](i,s),o[l](r,a),o.src=n},reportError(e){e&&!S.hasSpeedMetricsReported&&console.error(`{"type":"critical","desc":"ATF image failed to load","src":"${e.src}"}`)},getMainContentRect(){const e=document&&document[h]("main-content"),t=e&&e[0]&&e[0][h]("hp-grid-container");return t&&t[0]?t[0].getBoundingClientRect():e&&e[0]&&e[0].getBoundingClientRect()},loadImageIfVisible(){let{image:e,i:t,carouselOverride:n,immediate:a}=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};const i=e&&e.parentElement.classList.contains("vl-image-js")?e.parentElement:e,r="{}"!==JSON.stringify(S.mainContentRect)?S.mainContentRect.width+S.mainContentRect.left:null;if(o(i,r,200)){const n=document.createEvent("Event");n.initEvent(d,!1,!1),a&&a[p](v,1),e.dispatchEvent(n),S.queue.splice(t||0,1),a&&a.dataset&&"true"===a.dataset.itemCard&&S.addToSwapQueue(a)}},shouldLoadImageInHighPriority(e){if(e[m]("exclude-from-high-fetchpriority"))return!1;const t=S.atfImageList.map((e=>e[f]("img")[0])).includes(e),n="{}"!==JSON.stringify(S.mainContentRect)?S.mainContentRect.width+S.mainContentRect.left:null,a=o(e,n,200);return t&&a},loadImageInHighPriority(e,t){if(e&&e[p](v,1),t)return S.loadImageDiv({target:e.parentElement,fetchpriority:"high",vlAtf:!0});S.loadImage({target:e,fetchpriority:"high",vlAtf:!0}),e&&e.dataset&&"true"===e.dataset.itemCard&&!window.vertlandweb.isMobileLayout&&S.addToSwapQueue(e)},loadAll(){for(let e=S.queue.length-1;e>=0;e--){const t=document.createEvent("Event");t.initEvent("lazyLoad",!1,!1),S.queue[e].dispatchEvent(t),S.queue.splice(e||0,1)}if(!window.vertlandweb.isMobileLayout)for(let e=S.swapQueue.length-1;e>=0;e--){const t=document.createEvent("Event");t.initEvent(s,!1,!1),S.swapQueue[e].dispatchEvent(t),S.swapQueue.splice(e||0,1)}},iterateOverQueue(e){if(0!==S.queue.length)for(let t=S.queue.length-1;t>=0;t--)S.loadImageIfVisible(S.queue[t],t,e)},handler(){S.iterateOverQueue()},carouselHandler(e){if(!e||!e.el)return;const t=e.el.getBoundingClientRect(),n=2*t.width+t.left;S.iterateOverQueue(n)},getLoadTime:b,setLoadTime:L};e.exports=S},562:e=>{const t={init(){if(!window.ENABLE_VLP_COOKIE_OBSERVER)return;const e={},t={},n=[10,50,100,1e3,1/0];n.forEach((n=>{e[n]=0,t[n]=0}));const o={eventFamily:"VERTLAND",eventAction:"CLIENT_PAGE_VIEW",operationId:"4375194",flushImmediately:!1,eventProperty:{moduledtl:"mi:166198",imp:4560306}},a=()=>{o.eventProperty.moduledtl+=(()=>{const n=Object.keys(e).map((t=>`|r${t}:${e[t]}`)),o=Object.keys(t).map((e=>`|w${e}:${t[e]}`));return`${n.join("")}${o.join("")}`})();const n=new CustomEvent("pulsar",{detail:[o]});document.dispatchEvent(n)},i=(o,a)=>{const i=a?e:t;for(const e of n)if(o<=e){i[e]++;break}};try{const e=Object.getOwnPropertyDescriptor(Document.prototype,"cookie");Object.defineProperty(document,"cookie",{configurable:!0,enumerable:e.enumerable,get:function(){const t=Date.now(),n=e.get.call(document);return i(Date.now()-t,!0),n},set:function(t){const n=Date.now();e.set.call(document,t),i(Date.now()-n,!1)}})}catch(e){console.log("cookie observer failed",e)}window.addEventListener("load",(()=>{setTimeout((()=>{window._plsubtInp&&window._plsubtInp.registerUnloadCallback?window._plsubtInp.registerUnloadCallback(a):window.addEventListener("beforeunload",a)}),0)}))}};e.exports=t}},t={};function n(o){var a=t[o];if(void 0!==a)return a.exports;var i=t[o]={exports:{}};return e[o](i,i.exports,n),i.exports}n.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return n.d(t,{a:t}),t},n.d=(e,t)=>{for(var o in t)n.o(t,o)&&!n.o(e,o)&&Object.defineProperty(e,o,{enumerable:!0,get:t[o]})},n.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),(()=>{"use strict";var e=n(816),t=n.n(e),o=n(562),a=n.n(o);t().init(),a().init()})()})();</script><link rel="stylesheet" type="text/css" href="https://ir.ebaystatic.com/rs/c/globalheaderweb/index_lcNW.c9dfc033.css"><script>window.$i18n = {"follow/follow":{"saveSearchHeading":"Save search","emailMeNewItems":"Email me when new items match my search","cancel":"Cancel","save":"Save","savedSellerClippedText":"seller","savedSearchClippedText":"search","linkSave":"Save","linkSaved":"Saved","nameLabel":"Name","postTooltip":"We\'ll send you an email when there\'s something new.","postTooltipInfoOn":"To help you keep up, we can email you when there\'s something new.","postTooltipOff":"Turn off email alerts","postTooltipOn":"Turn on email alerts","postTooltipOffSuccess":"Email alerts turned off.","postTooltipOnSuccess":"Email alerts turned on.","postTooltipDismiss":"Dismiss the save search message.","errorMaxedSaveSearch":"You\'ve already saved the maximum number of searches. You need to unsave a search before adding another.","errorSave":"We had trouble saving this item. Please try again later.","errorUnsave":"We had trouble unsaving this item. Please try again later.","busy":"busy","loading":"Loading"},"locales":{"pageTitle":{"@target":{"Default":"Outlet","EBAY_DE":"eBay Marken Outlet - bis zu 70% Rabatt","EBAY_UK":"Brand Outlet"}},"pageDescription":{"@target":{"Default":"Get the best deals on Brand Outlet when you shop the largest online selection at eBay.com. Free postage on many items | Browse your favourite brands | affordable prices.","EBAY_DE":"Alle Fashion-Deals an einem Ort! Top-Marken ✓ bis zu 70% Rabatt ✓ attraktive Outlet-Preise ✓immer mit gratis Hin- und Rückversand ✓","EBAY_UK":"Buy from Brand Outlet and get the best fashion deals at the lowest prices on eBay! Save up to 70% on top brands and enjoy Free Delivery"}},"emptyState":"We weren\'t able to find your content. Please try again.","crumbA11y":"Page navigation","feedbackTextDWEB":"Feedback","feedbackTextDWEBA11Y":"What do you think of the new {vlpPageName} page?","openInNewTab":"Opens in a new window or tab","registerLiveEventError":"We had trouble setting an alert. Please try again later.","loggedOutNotice":"You\'ve signed out. See you again soon.","loggedOutFeedbackWithLink":"How was your experience? <a href=\\"{href}\\">Leave Feedback</a>","signInAgainLink":"<a href=\\"{href}\\">Sign in again</a>","home":"Home","tooltipTitle":"Looking for your old homepage?","tooltipSubTitle":"Find updates to saved searches and sellers here.","expandCategory":"Expand:","more":"More","following":"Following","saved":"Saved","open":"Open","close":"Close","localSearchPlaceholder":"Search for items near you","localSearchPlaceholderNoZipcode":"Search for local items","recentlyViewedTitle":"Recently viewed","dealsTitle":"Today\'s deals","watchedItemsTitle":"Watched items","piyiTitle":"Picks for you","setReminderText":"Set reminder for event","removeReminderText":"Remove reminder for event","explore":"Explore (New)","carouselPlay":"Play slideshow","carouselPause":"Pause slideshow","carouselPrevious":"Go to previous slide","carouselNext":"Go to next slide"}};</script><!--vertlandweb^s0-1-0-20 s0-1-0 20--><script id=ebay-rum-web></script><!--vertlandweb/--><script>\n      window.tempLazyLoadQueue = [];\n      window.addtoLazyLoad = function (config) {\n        if (typeof lazyLoad !== "undefined") {\n          lazyLoad.addToQueue(config.el, config.fit);\n        } else {\n          tempLazyLoadQueue.push(config);\n        }\n      };\n    </script><!-- SEO METADATA START --><link rel="alternate" href="https://pe.ebay.com" hreflang="es-PE" /><link rel="alternate" href="https://ni.ebay.com" hreflang="es-NI" /><link rel="alternate" href="https://ve.ebay.com" hreflang="es-VE" /><meta Property="og:type" Content="website" /><meta Property="og:image" Content="https://ir.ebaystatic.com/cr/v/c1/ebay-logo-1-1200x630-margin.png" /><meta name="twitter:description" content="Buy &amp; sell electronics, cars, clothes, collectibles &amp; more on eBay, the world&apos;s online marketplace. Top brands, low prices &amp; free shipping on many items." /><meta property="fb:app_id" content="102628213125203" /><meta name="twitter:card" content="summary" /><meta Property="og:site_name" Content="eBay" /><link rel="alternate" href="https://pa.ebay.com" hreflang="es-PA" /><meta Property="og:title" Content="Electronics, Cars, Fashion, Collectibles &amp; More | eBay" /><link rel="alternate" href="https://py.ebay.com" hreflang="es-PY" /><link rel="alternate" href="https://pr.ebay.com" hreflang="es-PR" /><link rel="alternate" href="https://www.ebay.com" hreflang="en-us" /><link rel="alternate" href="https://www.ebay.co.uk" hreflang="en-gb" /><title>Electronics, Cars, Fashion, Collectibles &amp; More | eBay</title><link rel="alternate" href="https://www.ebay.de" hreflang="de-de" /><link rel="alternate" href="https://www.ebay.com.au" hreflang="en-au" /><link rel="alternate" href="https://www.ebay.fr" hreflang="fr-fr" /><link rel="alternate" href="https://www.ebay.it" hreflang="it-it" /><link rel="alternate" href="https://www.ebay.es" hreflang="es-es" /><meta name="twitter:image" content="https://ir.ebaystatic.com/cr/v/c1/ebay-logo-1-1200x1200-margin.png" /><link rel="canonical" href="https://www.ebay.co.uk" /><meta name="description" content="Buy &amp; sell electronics, cars, clothes, collectibles &amp; more on eBay, the world&apos;s online marketplace. Top brands, low prices &amp; free shipping on many items." /><meta Property="og:description" Content="Buy &amp; sell electronics, cars, clothes, collectibles &amp; more on eBay, the world&apos;s online marketplace. Top brands, low prices &amp; free shipping on many items." /><link rel="alternate" href="https://www.ebay.ca" hreflang="en-ca" /><link rel="alternate" href="https://www.ebay.nl" hreflang="nl-nl" /><meta name="msvalidate.01" content="34E98E6F27109BE1A9DCF19658EEEE33" /><link rel="alternate" href="https://www.ebay.pl" hreflang="pl-pl" /><link rel="alternate" href="https://www.benl.ebay.be" hreflang="nl-be" /><link rel="alternate" href="https://www.befr.ebay.be" hreflang="fr-be" /><link rel="alternate" href="https://www.ebay.at" hreflang="de-at" /><link rel="alternate" href="https://www.ebay.ch" hreflang="de-ch" /><link rel="alternate" href="https://www.ebay.ie" hreflang="en-ie" /><link rel="alternate" href="https://www.ebay.com.my" hreflang="en-my" /><meta name="twitter:title" content="Electronics, Cars, Fashion, Collectibles &amp; More | eBay" /><meta name="twitter:site" content="@eBay" /><link href="https://i.ebayimg.com" rel="preconnect" /><link rel="alternate" href="https://www.ebay.com.sg" hreflang="en-sg" /><meta name="referrer" content="unsafe-url" /><link rel="alternate" href="https://www.ebay.ph" hreflang="en-ph" /><link rel="preconnect" href="https://ir.ebaystatic.com" /><link rel="alternate" href="https://www.cafr.ebay.ca" hreflang="fr-ca" /><link rel="alternate" href="https://www.ebay.com.hk" hreflang="zh-hk" /><link rel="alternate" href="https://cn.ebay.com" hreflang="zh-CN" /><link rel="alternate" href="https://il.ebay.com" hreflang="en-IL" /><link rel="alternate" href="https://pt.ebay.com" hreflang="pt-PT" /><link rel="alternate" href="https://by.ebay.com" hreflang="ru-BY" /><meta name="y_key" content="0090e7e28a2554d4" /><link rel="alternate" href="https://kz.ebay.com" hreflang="ru-KZ" /><link rel="alternate" href="https://br.ebay.com" hreflang="pt-BR" /><link rel="alternate" href="https://co.ebay.com" hreflang="es-CO" /><meta name="google-site-verification" content="N44szmI3uamPmsOzfSbiKbBd_834GucfjqGRRyXZ7wQ" /><link rel="alternate" href="https://mx.ebay.com" hreflang="es-MX" /><link rel="alternate" href="https://ar.ebay.com" hreflang="es-AR" /><link rel="alternate" href="https://bo.ebay.com" hreflang="es-BO" /><link rel="alternate" href="https://cl.ebay.com" hreflang="es-CL" /><meta Property="og:url" Content="https://www.ebay.co.uk" /><meta name="google-adsense-account" content="sites-6603353820027325" /><link rel="alternate" href="https://www.ebay.com" hreflang="x-default" /><link rel="alternate" hr

### Integrating requests with beautifulsoup

In [6]:
url = 'https://www.ebay.co.uk/'
response = requests.get(url)

soup = BeautifulSoup(response.text, "lxml")
soup

<!--vertlandweb#s0-1-0--><!DOCTYPE html>
<!--[if IE 9 ]>    <html class="ie9"> <![endif]--><!--[if (gt IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]--><head><!--vertlandweb^s0-1-0-4 s0-1-0 4--><!--vertlandweb/--><!--vertlandweb^s0-1-0-5 s0-1-0 5--><link href="//ir.ebaystatic.com" rel="dns-prefetch"/><link href="//secureir.ebaystatic.com" rel="dns-prefetch"/><link href="//i.ebayimg.com" rel="dns-prefetch"/><link href="//rover.ebay.com" rel="dns-prefetch"/><script>$ssgST=new Date().getTime();</script><!--vertlandweb/--><link as="image" crossorigin="" href="https://ir.ebaystatic.com/pictures/aw/pics/s_1x2.gif" rel="preload"/><meta charset="utf-8"/><link href="https://pages.ebay.com/favicon.ico" rel="icon"/><meta content="width=device-width, initial-scale=1, user-scalable=yes, minimum-scale=1" name="viewport"/><meta content="IE=edge" http-equiv="X-UA-Compatible"/><link href="https://srv.uk.ebayrtm.com" rel="preconnect"/><noscript><style>
        .js-only {
          display: none !important;
        }
      </style></noscript><script>
      window.layoutStart = Date.now();
      window.vertlandweb = {"isWebpSupported":false,"isLowBandwidth":false,"lazyLoadAll":true,"showSpeedInConsole":false,"isMobileLayout":false};
      // We need a way to pass the global config setting for enabling/disabling cookie-observer
      // inline script. Hence we get it from our global config and attach it to the window object.
      // So that the inline script injected as a part of include-html tag below has access to it.
      window.ENABLE_VLP_COOKIE_OBSERVER = false;
    </script><script data-type="inline_js" type="text/javascript">(()=>{var e={138:e=>{"use strict";var t=/(?:\d*\.)?\d+/g,n=[64,96,140,200,225,300,400,500,640,960,1200,1600],o={containsThumbs:function(e){return e.indexOf("thumbs")>-1},isZoomUrl:function(e){var t=this.containsThumbs(e)?8:7;return!(e.length!==t||!e[e.length-1].match("s-l"))||(console.debug("This image url is not valid Zoom format: ".concat(e.join("/"))),!1)},getParts:function(e,t){return e.split(t)},replaceType:function(e,t,n){var o=e,a=n?7:6,i=t.type||!t.cachedPage&&t.webp&&"webp";if(i){var r=this.getParts(o[a],".");r[1]=i,o[a]=r.join(".")}return o},getNearestSize:function(e){var t;for(t=0;t<n.length-1;t++)if(n[t]>=e)return n[t];return n[t]},getConnection:function(){return"undefined"!=typeof navigator&&navigator.connection&&navigator.connection.effectiveType},isLowBandwidth:function(e){var t=this.getConnection();return t?["slow-2g","2g","3g"].filter((function(e){return e===t})).length:!e.cachedPage&&e.lowBandwidth},replaceSize:function(e,n,o){var a,i=e,r=o?7:6;a=n.size?n.size:i[r].match(t)[0],window.innerWidth<a&&n.safeSizeImages&&(a=this.getNearestSize(window.innerWidth));var d=window.devicePixelRatio||1;return!n.disableHDSizing&&d>1&&!n.lowBandwidth&&(n.disable3xSizing?a*=2:a*=d),i[r]=i[r].replace(t,this.getNearestSize(a)),i},transformUrl:function(e){var t=this.getParts(e.src,"/"),n=this.containsThumbs(t);return this.isZoomUrl(t)?(t=this.replaceSize(t,e,n),(t=this.replaceType(t,e,n)).join("/")):e.src}};e.exports=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};return e.lowBandwidth=o.isLowBandwidth(e),function(t,n,a){try{var i=Object.create(e);return i.src=t,n&&(i.size=n),a&&(i.type=a),o.transformUrl(i)}catch(e){return console.debug("There was an error trying to transform this zoom url: ".concat(t,", size: ").concat(n,", type: ").concat(a,", ").concat(e.stack)),t}}},e.exports.helpers=o},519:e=>{e.exports=(e,t,n)=>{if(!e)return!1;const o=n||0,a=window.innerHeight,i=t||window.innerWidth,r=e.getBoundingClientRect(),d=r.top<=a+o&&r.top+r.height>=0,s=r.left<i&&r.left+r.width>0;return d&&s}},816:(e,t,n)=>{const o=n(519),a=n(138),i="load",r="error",d="lazyLoad",s="lazyLoadSwap",l="addEventListener",c="removeEventListener",u="removeAttribute",m="hasAttribute",g="data-load-time",p="setAttribute",w="getAttribute",h="getElementsByClassName",f="querySelectorAll",v="data-vl-atf",y=window.performance&&window.performance.timing,I=Array.prototype.slice,b=e=>parseInt(e[w](g)),L=e=>{const t=Date.now();return e[p](g,t),t},T="data-m-atf",E="vl-atf-module-js",S={hasSpeedMetricsReported:!1,queue:[],swapQueue:[],atfImageList:[],mainContentRect:{},startTime:"undefined"==typeof $ssgST?Date.now():$ssgST,init(){window.lazyLoadInit=Date.now(),S.zoomClient=a({webp:window.vertlandweb.isWebpSupported,lowBandwidth:window.vertlandweb.isLowBandwidth,cachedPage:!1,disableHDSizing:!window.vertlandweb.isMobileLayout}),window.lazyLoad=window.lazyLoad||{},window.lazyLoad.addToQueue=(e,t)=>{if(e[u]("onerror"),e[u]("onload"),"{}"===JSON.stringify(S.mainContentRect)&&(S.mainContentRect=S.getMainContentRect()),0===S.atfImageList.length&&(S.atfImageList=S.buildATFImageList()),e[m]("data-load-immediately"))return t?S.loadImageDiv({target:e.parentElement}):S.loadImage({target:e});if(S.shouldLoadImageInHighPriority(e))return S.loadImageInHighPriority(e,t);if(t){const t=e.parentElement;t[l](d,S.loadImageDiv),S.queue.unshift(t),S.loadImageIfVisible({image:t,immediate:e})}else e[l](d,S.loadImage),S.queue.unshift(e),S.loadImageIfVisible({image:e,immediate:e})},window[l](i,S.loadAll),window.tempLazyLoadQueue&&(window.tempLazyLoadQueue.forEach((e=>{let{el:t,fit:n}=e;window.lazyLoad.addToQueue(t,n)})),window.tempLazyLoadQueue=[]),window[l](i,S.reportATFTimeFromPageLoad)},tearDown(){window[c](i,S.loadAll),window[c](i,S.reportATFTimeFromPageLoad)},buildATFImageList:()=>I.call(document[h](E),0,2).reduce(((e,t)=>e.concat(I.call(t[h]("vl-image-js")))),[]),reportATFTimeFromPageLoad(){S.setOKToReport(!0),S.reportATFTime()},reportATFTime(){const e=S.getATFMetrics(!0);S.showSpeedInConsole(e),delete e.lastImageLoaded,S.hasSpeedMetricsReported=!0;const t=new Event("site-speed-ebay.metricsData");t.detail=e,document.dispatchEvent(t)},getModuleATFMetrics(){const e=Array.from(document[h](E)).slice(0,3);let t="";return e.map((e=>{const n=Array.from(e[f](`[${v}]`)),o=n.length||0;e.setAttribute("data-m-size",o);const a=n.sort(((e,t)=>b(t)-b(e)))[0];a&&(e.setAttribute(T,y?b(a)-y.responseStart:0),t+=`${e[w]("data-m-id")}:${e[w](T)}:${o}|`)})),t},getATFMetrics(){const e={},t=S.getATFLoadedImages(),n=t.sort(((e,t)=>b(t)-b(e))),o=n[0],a=n[n.length-1],i=o?b(o):Date.now(),r=a?b(a):Date.now();return e.jsljgr2=i-S.startTime,y&&(e.i_29i=i-y.responseStart),y&&(e.i_1i=r-y.responseStart),e.i_0i=t.length,e.lastImageLoaded=o,e.atfdtls=o?S.getModuleATFMetrics():null,window.vlServiceTime>0&&(e.i_2i=window.vlServiceTime),e},getATFLoadedImages(){const e=I.call(document[h](E),0,2).reduce(((e,t)=>e.concat(I.call(t[f](`[${v}]`)))),[]),t=e.filter((e=>e[m](g)&&!e[m]("exclude-from-high-fetchpriority")));return window.vertlandweb.showSpeedInConsole&&console.log("Lazyload Init() getATFLoadedImages() loadedImageList",t),e.length===t.length&&S.setOKToReport(!1),t},setOKToReport(e){S.oKToReport=e},showSpeedInConsole(e){window.vertlandweb.showSpeedInConsole&&console.log("Speed data:",Object.assign({},e))},getSrc(e){const t=e.dataset;return S.zoomClient(t.src,parseInt(t.size,10))},loadImage(e){const t=e.target,n=t.dataset;let o=S.getSrc(t);e.fetchpriority&&t[p]("fetchpriority",e.fetchpriority),"true"!==n.itemCard||n.vlAtf||window.vertlandweb.isMobileLayout||(o=S.zoomClient(n.src,parseInt(n.highResSize,10))),t[l](i,S.imageLoadHandler),t[l](r,S.imageLoadErrorHandler),t.src=o},addToSwapQueue(e){e[l](s,S.loadSwapImage),S.swapQueue.push(e)},loadSwapImage(e){const t=e.target,n=t.dataset,o=S.zoomClient(n.src,parseInt(n.highResSize,10)),a=new Image;a.src=o,a.onload=()=>{t.src=o,t[c](s,S.loadSwapImage)}},imageLoadHandler(e){const t=e.target;t&&(L(t),t[c](i,S.imageLoadHandler),t[c](r,S.imageLoadErrorHandler),t.style.opacity=1)},imageLoadErrorHandler(e){const t=e.target;t&&(L(t),t[c](d,S.loadImage),t.style.opacity=0,S.reportError(t))},loadImageDiv(e){const t=e.target,n=S.getSrc(t);if(!n)return void console.error("Can't find source of image",t);let o=t.children[1];e.fetchpriority&&o[p]("fetchpriority",e.fetchpriority);const a=function(){t&&o&&(L(o),t.removeChild(o),o=null,t[c](d,S.loadImage),t.style.backgroundImage="none",t.children[0].style.opacity=1,S.reportError(t))},s=function(){t&&o&&(L(o),o.src=n,o[c](i,s),o[c](r,a),t.style.backgroundImage=`url('${n}')`,t.children[0].style.opacity=0)};o[l](i,s),o[l](r,a),o.src=n},reportError(e){e&&!S.hasSpeedMetricsReported&&console.error(`{"type":"critical","desc":"ATF image failed to load","src":"${e.src}"}`)},getMainContentRect(){const e=document&&document[h]("main-content"),t=e&&e[0]&&e[0][h]("hp-grid-container");return t&&t[0]?t[0].getBoundingClientRect():e&&e[0]&&e[0].getBoundingClientRect()},loadImageIfVisible(){let{image:e,i:t,carouselOverride:n,immediate:a}=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};const i=e&&e.parentElement.classList.contains("vl-image-js")?e.parentElement:e,r="{}"!==JSON.stringify(S.mainContentRect)?S.mainContentRect.width+S.mainContentRect.left:null;if(o(i,r,200)){const n=document.createEvent("Event");n.initEvent(d,!1,!1),a&&a[p](v,1),e.dispatchEvent(n),S.queue.splice(t||0,1),a&&a.dataset&&"true"===a.dataset.itemCard&&S.addToSwapQueue(a)}},shouldLoadImageInHighPriority(e){if(e[m]("exclude-from-high-fetchpriority"))return!1;const t=S.atfImageList.map((e=>e[f]("img")[0])).includes(e),n="{}"!==JSON.stringify(S.mainContentRect)?S.mainContentRect.width+S.mainContentRect.left:null,a=o(e,n,200);return t&&a},loadImageInHighPriority(e,t){if(e&&e[p](v,1),t)return S.loadImageDiv({target:e.parentElement,fetchpriority:"high",vlAtf:!0});S.loadImage({target:e,fetchpriority:"high",vlAtf:!0}),e&&e.dataset&&"true"===e.dataset.itemCard&&!window.vertlandweb.isMobileLayout&&S.addToSwapQueue(e)},loadAll(){for(let e=S.queue.length-1;e>=0;e--){const t=document.createEvent("Event");t.initEvent("lazyLoad",!1,!1),S.queue[e].dispatchEvent(t),S.queue.splice(e||0,1)}if(!window.vertlandweb.isMobileLayout)for(let e=S.swapQueue.length-1;e>=0;e--){const t=document.createEvent("Event");t.initEvent(s,!1,!1),S.swapQueue[e].dispatchEvent(t),S.swapQueue.splice(e||0,1)}},iterateOverQueue(e){if(0!==S.queue.length)for(let t=S.queue.length-1;t>=0;t--)S.loadImageIfVisible(S.queue[t],t,e)},handler(){S.iterateOverQueue()},carouselHandler(e){if(!e||!e.el)return;const t=e.el.getBoundingClientRect(),n=2*t.width+t.left;S.iterateOverQueue(n)},getLoadTime:b,setLoadTime:L};e.exports=S},562:e=>{const t={init(){if(!window.ENABLE_VLP_COOKIE_OBSERVER)return;const e={},t={},n=[10,50,100,1e3,1/0];n.forEach((n=>{e[n]=0,t[n]=0}));const o={eventFamily:"VERTLAND",eventAction:"CLIENT_PAGE_VIEW",operationId:"4375194",flushImmediately:!1,eventProperty:{moduledtl:"mi:166198",imp:4560306}},a=()=>{o.eventProperty.moduledtl+=(()=>{const n=Object.keys(e).map((t=>`|r${t}:${e[t]}`)),o=Object.keys(t).map((e=>`|w${e}:${t[e]}`));return`${n.join("")}${o.join("")}`})();const n=new CustomEvent("pulsar",{detail:[o]});document.dispatchEvent(n)},i=(o,a)=>{const i=a?e:t;for(const e of n)if(o<=e){i[e]++;break}};try{const e=Object.getOwnPropertyDescriptor(Document.prototype,"cookie");Object.defineProperty(document,"cookie",{configurable:!0,enumerable:e.enumerable,get:function(){const t=Date.now(),n=e.get.call(document);return i(Date.now()-t,!0),n},set:function(t){const n=Date.now();e.set.call(document,t),i(Date.now()-n,!1)}})}catch(e){console.log("cookie observer failed",e)}window.addEventListener("load",(()=>{setTimeout((()=>{window._plsubtInp&&window._plsubtInp.registerUnloadCallback?window._plsubtInp.registerUnloadCallback(a):window.addEventListener("beforeunload",a)}),0)}))}};e.exports=t}},t={};function n(o){var a=t[o];if(void 0!==a)return a.exports;var i=t[o]={exports:{}};return e[o](i,i.exports,n),i.exports}n.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return n.d(t,{a:t}),t},n.d=(e,t)=>{for(var o in t)n.o(t,o)&&!n.o(e,o)&&Object.defineProperty(e,o,{enumerable:!0,get:t[o]})},n.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),(()=>{"use strict";var e=n(816),t=n.n(e),o=n(562),a=n.n(o);t().init(),a().init()})()})();</script><link href="https://ir.ebaystatic.com/rs/c/globalheaderweb/index_lcNW.c9dfc033.css" rel="stylesheet" type="text/css"/><script>window.$i18n = {"follow/follow":{"saveSearchHeading":"Save search","emailMeNewItems":"Email me when new items match my search","cancel":"Cancel","save":"Save","savedSellerClippedText":"seller","savedSearchClippedText":"search","linkSave":"Save","linkSaved":"Saved","nameLabel":"Name","postTooltip":"We'll send you an email when there's something new.","postTooltipInfoOn":"To help you keep up, we can email you when there's something new.","postTooltipOff":"Turn off email alerts","postTooltipOn":"Turn on email alerts","postTooltipOffSuccess":"Email alerts turned off.","postTooltipOnSuccess":"Email alerts turned on.","postTooltipDismiss":"Dismiss the save search message.","errorMaxedSaveSearch":"You've already saved the maximum number of searches. You need to unsave a search before adding another.","errorSave":"We had trouble saving this item. Please try again later.","errorUnsave":"We had trouble unsaving this item. Please try again later.","busy":"busy","loading":"Loading"},"locales":{"pageTitle":{"@target":{"Default":"Outlet","EBAY_DE":"eBay Marken Outlet - bis zu 70% Rabatt","EBAY_UK":"Brand Outlet"}},"pageDescription":{"@target":{"Default":"Get the best deals on Brand Outlet when you shop the largest online selection at eBay.com. Free postage on many items | Browse your favourite brands | affordable prices.","EBAY_DE":"Alle Fashion-Deals an einem Ort! Top-Marken ✓ bis zu 70% Rabatt ✓ attraktive Outlet-Preise ✓immer mit gratis Hin- und Rückversand ✓","EBAY_UK":"Buy from Brand Outlet and get the best fashion deals at the lowest prices on eBay! Save up to 70% on top brands and enjoy Free Delivery"}},"emptyState":"We weren't able to find your content. Please try again.","crumbA11y":"Page navigation","feedbackTextDWEB":"Feedback","feedbackTextDWEBA11Y":"What do you think of the new {vlpPageName} page?","openInNewTab":"Opens in a new window or tab","registerLiveEventError":"We had trouble setting an alert. Please try again later.","loggedOutNotice":"You've signed out. See you again soon.","loggedOutFeedbackWithLink":"How was your experience? <a href=\"{href}\">Leave Feedback</a>","signInAgainLink":"<a href=\"{href}\">Sign in again</a>","home":"Home","tooltipTitle":"Looking for your old homepage?","tooltipSubTitle":"Find updates to saved searches and sellers here.","expandCategory":"Expand:","more":"More","following":"Following","saved":"Saved","open":"Open","close":"Close","localSearchPlaceholder":"Search for items near you","localSearchPlaceholderNoZipcode":"Search for local items","recentlyViewedTitle":"Recently viewed","dealsTitle":"Today's deals","watchedItemsTitle":"Watched items","piyiTitle":"Picks for you","setReminderText":"Set reminder for event","removeReminderText":"Remove reminder for event","explore":"Explore (New)","carouselPlay":"Play slideshow","carouselPause":"Pause slideshow","carouselPrevious":"Go to previous slide","carouselNext":"Go to next slide"}};</script><!--vertlandweb^s0-1-0-20 s0-1-0 20--><script id="ebay-rum-web"></script><!--vertlandweb/--><script>
      window.tempLazyLoadQueue = [];
      window.addtoLazyLoad = function (config) {
        if (typeof lazyLoad !== "undefined") {
          lazyLoad.addToQueue(config.el, config.fit);
        } else {
          tempLazyLoadQueue.push(config);
        }
      };

Data Extraction

In [7]:
url = 'https://www.ebay.co.uk/sch/i.html?_nkw=laptops&_sacat=0&_from=R40&_trksid=p2334524.m570.l1313&rt=nc&_odkw=generator&_osacat=0&LH_All=1'
response = requests.get(url)

soup = BeautifulSoup(response.text, 'lxml')

In [8]:
# PRODUCTS EXTRACTION 
names = soup.find_all('span', role='heading' )

# PRODUCT NAMES
product_names = []
for name in names[2:]:
    product_names.append(name.get_text(strip=True))

In [41]:
product_names

['Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN 32GB RAM 1TB SSD WEBCAM WIFI',
 'FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WARRANTY FREE WINDOWS 11 UPGRADE',
 'FAST CHEAP TOP BRAND INTEL CORE i5 8TH GEN 16GB RAM 480GB SSD WINDOWS 11 LAPTOP',
 'CUSTOM FAST CHEAP LAPTOP Intel Core i3/i5 - Windows 10 - WiFi',
 'SUPER FAST WINDOWS 11 CHEAP LAPTOP INTEL CORE I5 4/8/16GB RAM 1TB HDD SSD WEBCAM',
 'Lenovo MIIX 320-10ICR 2in1 tablet - Intel Atom x5 Z8350 4GB RAM - 64GB (GRADE A)',
 'CHEAP FAST Laptop DELL Quad Core 2.6GHZ Windows 10 SSD 4K HDMI WIFI WEBCAM',
 'Stone StoneBook Mini M10A 11.6" Laptop 120GB SSD 4GB RAM CHEAP COMPACT + PSU #1i',
 'Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN 32GB RAM 1TB SSD WEBCAM WIFI',
 'FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WARRANTY FREE WINDOWS 11 UPGRADE',
 'Lenovo ThinkPad T480 i5-8250U up to 64GB Ram up to 2TB SSD FHD Windows Laptop',
 'Dell Latitude 7420 i5-1145G7 11th Gen 16GB Ram 256GB SSD FHD Windows 11 Laptop',
 'FAST CHEAP LAPTOP i3 i5 i7 8GB 16GB RAM SSD 12.5"  14" 15.6" Win 10 or 11 WEBCAM',
 'Lenovo Thinkpad Laptop Intel Core i7 i5 16GB 512GB SSD Windows 11 T470 T490 Yoga',
 'New 2024 Lenovo V15 Gen 4 AMD Athlon Silver 7120U 8GB RAM 256GB SSD FHD Win 11',
 'CHEAP FAST Intel Core i5 LAPTOP - Windows 11 - CHOOSE Your Spec 16GB 512GB SSD',
 'New listingDell Latitude 3301 i3-8145U 4GB 128GB NVMe SSD, Windows 11 Pro',
 'Dell latitude E7270 12.5" I5 8GB 128GB SSD Windows 10 Pro + Laptop Charger',
 'HP 250 G7 INTEL CELERON WINDOWS 11 LAPTOP 15" 128GB SSD HD WEBCAM BLUETOOTH',
 'ASUSTeK  E201NA, Intel Celeron N3350, 4GB DDR3, 32GB SSD, Win10 Pro, 11.6"',
 'CHEAP FAST Top Brand Windows 10/11 Laptop i3/i5 32GB Ram 256GB SSD/ 1TB SSD WIFI',
 'Lenovo ThinkPad L490 i5-8265U Quad Core 16GB 256GB SSD Windows 11 Pro Laptop',
 'FAST CHEAP INTEL CORE i3 / i5 LAPTOP - Windows 10 + 8GB RAM + 120GB SSD + WiFi',
 'Windows 11 Laptop HP Dell Lenovo Intel Core i3 i5 8GB 128GB SSD Warranty',
 "Samsung Galaxy Book Go 14'' LTE Laptop 4GB RAM 128GB Silver NP345XLA - Good",
 '10.1" PANASONIC TOUGHPAD FZ-G1 MK2 FZ-G1FA-50BE i5-4310U 2.00GHZ 8GB 256GB LTE',
 'Acer Foldable 2-in-1 Chromebook R11 C738T-C7KD 11.6 inch Laptop 4GB RAM 16GB SSD',
 'Lenovo ThinkPad T480 i5-8250U up to 64GB Ram up to 2TB SSD FHD Windows Laptop',
 'Acer laptop intel i3 2.3GHz 256GB SSD & 500GB 8GB Ram 15.6 Screen Win 11 or 10',
 'CHEAP FAST Intel Core i5 LAPTOP - Windows 11 - CHOOSE Your Spec 16GB 512GB SSD',
 'New listingLenovo ThinkPad X280 i5-8350U 1.7GHZ Vpro 12.5", 16GB RAM ,BIOS BOOT LAPTOP,SL36',
 'New listingDell Latitude E6330 Laptop - i5-3340M, 8GB RAM, 240GB SSD, Windows 10, 13.3"',
 'Dell Latitude Windows 11 5470/7470 Core i5-6200U 32GB Ram 1TB SSD',
 'New listingDell Inspiron 15 7577 Laptop - i7 32gb RAM GTX 1060 1 tb SSD + 1tb HDD',
 'HP Chromebook 11A G6 EE A4-9120C 4GB RAM 16GB eMMc Chrome OS Laptop Notebook',
 'dell latitude 3190 laptop',
 'HP 14s-dq5013na Laptop - Core™ i3',
 'SGIN 15.6 Inch Laptop Intel Celeron Quad-Core Up To 2.8 GHz 4GB RAM 256GB SSD',
 'Cheap Laptop HP Dell  Lenovo Intel iCore i3 i5 i7 8GB 128 GB SSD Windows 11',
 'SGIN Laptop 17.3 Inch Laptops 8GB RAM 512GB SSD FHD IPS 2.4/5G WiFi BT5.0 USB',
 'Laptop Dell  Windows 11 CORE i5 GEN 6 - 12TH GEN 64GB RAM 1TB SSD WEBCAM WIFI',
 'New listing14" WIndows 11 Pro Laptop Intel Celeron N4000 6GB RAM 128GB SSD Lot 1  (Hea)Charity item',
 'Cheap Fast Windows 10 Laptop CORE i5 8GB RAM 256GB SSD WIFI',
 'Dell Latitude 7400 Core i5-8365U 8GB Ram 256GB SSD FHD Touchscreen Laptop Win11',
 'New listingMicrosoft Surface Laptop Go 2 12.4" (128GB SSD, Intel Core i5 11th Gen., 8GB)',
 'New listingHP 350 Laptop, i5 5th Gen, 6GB RAM, 500GB HDD, Windows 11 Pro, No Battery',
 'Cheap Fast iCore Laptop Dell HP Core i3 i5 AMD 8GB RAM 128 GB SSD Windows 11',
 'Panasonic Toughbook CF-20 Rugged Laptop Tablet Win 10 Pro & Keyboard Up To 2 Tb',
 'New listingDell Laptop 7320 Windows 11 Pro i7 11th Gen 13.3 Inch 16GB RAM 256GB SSD',
 'Dell Laptop I5 7280 8GB 128GB SSD WINDOWS 11 + Laptop Charger',
 'Dell Latitude 5400 14" i5 8th Gen SSD 256GB RAM 16GB Win 10. Dell Original PSU.',
 'New listingDell Inspiron 15 5000 laptop 4GB RAM 15.6” HD Display',
 'New listingMSI Gf62 8RC 15.6” Faulty Laptop i5 8th Gen 16GB GTX 1050 2GB 120GB NVME + 500GB',
 'New listingLenovo ThinkPad L480 14” I5-8350u, 8GB RAM, 256GB SSD',
 'Lenovo ThinkPad X230 12.5" Laptop, Core i5 3rd Gen, 8GB RAM, 120GB SSD, Win 10',
 'New listingHP ProBook 450 G7 15.6" Laptop - Intel Core I5-10210U, 1.6GHz, 8GB RAM',
 '10.1" PANASONIC TOUGHPAD FZ-G1 MK4 FZ-G1R0-53TE i5-6300U 2.40GHZ 4GB 128GB LTE',
 'New listingFujitsu laptop uh572 I5 3317u HD screen 8GB RAM 120GB SSD Windows Home',
 'HP EliteBook 840 G5 Core I7 16GB RAM 512GB SSD',
 'Lenovo ThinkPad Windows 11 , 500GB SSD, Intel i5, 8GB Laptop - Same day dispatch',
 'New listingDell Latitude 7390 Laptop 13.3", 8th Gen, 256Gb SSD, 8Gb Ram with 6 mth warranty',
 'FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WARRANTY WINDOWS 11 Pro',
 'Dell Chromebook 3180 11.6 Inch Intel Celeron N3060 16GB eMMC Laptop',
 'Lenovo V155-15API Laptop - 15.6” FHD - AMD Ryzen 3 3500U - 8GB RAM - 256GB SSD',
 'Lenovo Thinkpad Laptop Intel Core i7 i5 16GB 512GB SSD Windows 11 T470 T490 Yoga',
 'New listingHP omen 16-n0002na - NO SSD - Ryzen 7 6000 series - 16GB - Damaged',
 'HP EliteBook 840 G6 i7-8565U up to 64GB Ram up to 2TB SSD FHD Windows 11 Laptop',
 'Dell Latitude 5400 16GB RAM 256GB NVMe i5-8265U 8th Gen SSD Windows 11 #9',
 'Dell Vostro 5515 15.6” FHD FAST Laptop AMD Ryzen 5 5500U 8GB RAM 256GB SSD, Good',
 'New listingToshiba Satellite L850D 15.6" HD SCREEN 8GB DDR3 RAM 180GB SSD Windows 11 Home',
 'Dell Chromebook 3100 11.6" Celeron N4020 4GB 16GB USB-C Port 2021 No Charger',
 'Lenovo ThinkPad Windows 11 , 240GB SSD, Intel i5, 8GB Laptop - Same day dispatch',
 'New listingHP Stream Laptop',
 'New listingXPS 13 9365 2-in-1 i5, 476GB SSD, 8GB Ram windows 11 Pro 3200 x1800 touchscreen',
 'Lenovo L380 Touchscreen Laptop i5-8250U 1.6ghz 8GB 256GB SSD Windows 11 Office',
 'SGIN  17.3"  Laptop Notebook FHD Intel Celeron N4020 8GB DDR4 256GB SSD 2.6GHz',
 'New listingLenovo ThinkPad x220 i7 2640M 2.8Ghz 16GB RAM 256GB SSD (1103)',
 'New listingGeoBook Laptop 11.6" Full Microsoft Office Windows 11 Pro Ram 64GB SSD',
 'Dell Latitude 7490 Core i7-8650U up to 64GB Ram up to 2TB SSD FHD Laptop',
 'Fast HP 2 in 1 Convertible Laptop Tablet Intel i7 8GB RAM 128GB SSD Touchscreen',
 'PANASONIC TOUGHBOOK CF-19 MK3 | 10" TOUCHSCREEN 1.20GHZ 4GB 512GB',
 'New listingHP Elitebook 840 G5 14" FHD i5-8350 1.7GHZ 8GB RAM 256GB SSD DRIVE WIN 11 ,SL17',
 'Fast Cheap Intel Core i5 7th Gen Windows 10 8GB RAM 512GB SSD WI-FI LAPTOP',
 'Acer Nitro V 16 Gaming Laptop ANV16-41 Black #nb',
 'SGIN Laptop 4GB DDR4 512GB SSD 15.6 Inch Computer Quad-Core 2.5GHz FHD Mini HDMI',
 'HP 17-cp2006na Laptop - Ryzen™ 3',
 'LAPTOP Job lot 20pcs HP DELL LENOVO Core i5 For parts spare parts',
 'Lenovo Yoga ThinkPad 11e Chromebook Foldable Touchscreen 11.6 inch Laptop',
 'CHEAP FAST WINDOWS 11 LAPTOP INTEL CORE i5 32 RAM 1TB SSD WITH 1 YEAR WARRANTY',
 'New listingDell Latitude 5300 Touchscreen i5-8365U 8th Gen 256GB NVME 8GB RAM  Grade A',
 'Fast cheap Toshiba Laptop i3 256GB SSD 8GB RAM 15.6" screen Windows 11 or 10',
 'Panasonic Toughbook FZ-G1 i5 4310 2.0GHz 4GB 120GB SSD Touch 10.1" Windows 10',
 'New listingDell Latitude 7420 Laptop 14" FHD Intel Core i5-1135G7 8GB RAM 256GB SSD Win 11',
 'Microsoft Surface Laptop 2 13.5 inch 128GB Intel Core i5 8th Gen 8GB Touchscreen',
 'New listingHP PROBOOK 455 G6 Ryzen 3 2200U 8GB Radeon Graphics 128GB Windows 11 #154',
 'Cheap Laptop Lenovo HP Dell Core i3 i5 8GB RAM 128 GB SSD Windows 10 Win',
 'ASUS E410 14" Laptop Intel Celeron 4gb RAM 64gb eMMC Full HD purple',
 'HP 14s-dq5011na Laptop - Core™ i3',
 'HP Pavilion SE 15-fd0052na - Intel® Processor N100',
 'LAPTOP Job lot 18pcs HP DELL LENOVO Core i5 For parts spare parts',
 'New listingHP Pavilion x360 14 11th Gen Intel Core i7 2.80GHz 16GB 512GB SSD 2-in-1 Laptop',
 'New listingLenovo ThinkPad X390 i5-8365U 1.60GHz 8GB 256GB 13.3" No O/S Faults See Details',
 'FAST CHEAP LAPTOP i3 i5 i7 8GB 16GB RAM SSD 12.5"  14" 15.6" Win 10 or 11 WEBCAM',
 'CHEAP  HP 250  G7 Laptop  Intel Celeron 4GB 128GB SSD 15.6". Windows 10',
 'Lenovo ThinkPad T480s 14" 256GB SSD Intel Core i5-8350U 8th Gen, 16GB RAM Win 11',
 'New listingHP 15-DB0017NV LAPTOP - W11 P-4GB-128GB-AMD E2-9000e@1.50GHz',
 'New listingLenovo IdeaPad 310-15ISK 15.6" i7-6500U 2.5GHZ 12GB RAM 500GB EVO SSD 920MX,SL20',
 'HP Elitebook 755 G5 Ryzen 5 Pro 2500U 2GHz 8GB RAM 256GB SSD 15.6" Laptop STA',
 'HP EliteBook X360 1030 G2 Corei5-7300U 2.6GHz-8GB RAM-512GB SSD-Ref:2061',
 'New listingJob lot of 4 HP Laptops Elitebook/Zbook/Ryzen 5/I7 8th Gen- Spares or Repairs',
 'New listinglenovo ideapad  17.3” Big Screen 1TB HDD 12GB RAM Slim Laptop Intel Pentium Gold',
 'New listingHP EliteBook 840 G5 14" Laptop I7-8565U 8GB RAM / 256GB SSD Windows 11 Pro',
 'New listingLenovo X1 Carbon 3rd Gen i7-5600U 2.6GHz 8GB RAM 256GB SSD QHD 14" 4G LTE Win 10',
 'CHEAP FAST Intel Core i5 6th GEN LAPTOP - Windows 11 - 16GB RAM 512GB SSD',
 'Dell Laptop Latitude 7420 14" Laptop I7-1185G7 16GB RAM 240GB SSD Windows 11 Pro',
 'HP Pavilion x360 14-ek1000na Convertible Touchscreen Laptop – Core™ i5',
 'ASUS Chromebook Flip C214M 11.6" Laptop Tablet 4GB 32GB Google Touchscreen',
 'Laptop Dell Latitude 7490 14-inch Core i5 8TH GEN 16GB RAM 512GB SSD WINDOWS 11',
 'New listingDell Laptop Inspiron 1545 15.6" Celeron T33003GB RAM 240Gb HDD Spares/RepairCharity item',
 'Acer Chromebook 12" Spin 512 R851TN-P4VW TouchScreen 2in1 8GB 64GB 2020 GA',
 'NEW LENOVO 100E 2ND GEN WINDOWS 10 11.6" HD LAPTOP AMD 3015E 64GB SSD USB C SD',
 'New listingDell Latitude 7300 - Intel Core i5-8265U - 8GB RAM - 256GB SSD W11 Pro Grade B',
 'HP 14s-dq0011na Laptop - Intel® Pentium® with Microsoft 365 Personal 1 year',
 'Generic Fast Cheap Intel Core i5 6thGen Win 10 8GB RAM 240GB SSD WI-FI LAPTOP',
 'HP Touch Screen 2-in-1 Laptop 4GB RAM 128GB SSD 11.6" Touch W10 Pro ProBook x360',
 'GETAC V110 G3 WINDOWS 11 RUGGED TABLET LAPTOP INTEL I5 6200U TOUCH 128GB NVM 8GB',
 'Toshiba Portege X20W-D-122 | 12.5" | i7-7500U I | 16GB | 256GB SSD | Touchscreen',
 'New listingLenovo ThinkPad E560 Laptop i5 16GB RAM 180GB SSD Windows 11 Pro FREE DELIVERY',
 "New listingHP 15 BR018/4415U/4GB RAM/1TB HDD 'Very slow'",
 'Dell Vostro 5471, i5-8250U, 16GB RAM, 256GB SSD, Win 11 Pro *B GRD + BTRY ISSUE*',
 'HP EliteBook 840 G6 i5-8265U 16GB Ram 256GB NVMe Windows 11 Pro',
 'New listingHP Elitebook 755 G5 Ryzen 5 Pro 2500U 2.0GHz 8GB 256GB 15.6" Radeon Laptop 1002',
 'Dell Latitude 5410 Laptop, 14" Core i5 10th Gen, 8GB RAM, 256GB SSD, Windows 11',
 'New listingDell Inspiron 3558 15.6" Laptop i3-5005U 2.00GHz 8GB RAM 500GB HDD *Keys',
 'Fast Cheap Intel Core i5 8th Gen Laptop With Windows 11 8GB RAM 256GB SSD Wifi',
 'Fast Cheap Dell Gaming Laptop i7 Up To 3.40GHz 32GB RAM 1TB SSD Win11 Computer',
 'Dell Latitude 7220 Rugged Extreme Tablet i5-8365U 8GB 128GB WIN 11 Pro B Grade',
 'New listingDell Latitude 3410 14" FHD Laptop - Core i5-10210U 1.60Ghz, 16GB RAM, 256GB SSD',
 'New listingLenovo ideapad Y900-17ISK Laptop and Charger',
 'Lenovo Tablet 10" Windows 11 Tablet 4GB RAM 64GB SSD FULL HD HDMI +Stylus',
 'New listingLenovo Thinkpad laptop i7 8th GEN 8650U 512GB SSD 15.6" Screen Windows 11.',
 'New listingLenovo IdeaPad S145-15IWL 15.6" (128GB SSD, Intel  Pentium Gold) Platinum Grey',
 'Lenovo ThinkPad X13 Gen 1  - i5-10210U - 16GB RAM - 256GB SSD',
 'Super Fast Kali Linux Laptop 16GB RAM 1TB M.2 SSD Intel Core i5 Webcam Wi-Fi',
 'Lenovo ThinkPad X395 AMD Ryzen 5 Pro 3500U 8GB Ram 256GB SSD FHD Vega 8 Laptop',
 '*EXCELLENT BATTERY*Dell Latitude 5490 i5-8th Gen 16GB 256GB SSD 14" FHD Win 11 ✅',
 'New listingasus x540s laptop',
 'New listingHP 450 G5 Laptop, i5-8250U, 8GB DDR4, 256GB NVMe',
 'New listingHP G61',
 'New listingLenovo IP Slim 3 Chrome 14" (64GB eMMC, MediaTek Kompanio 520,',
 'New listingHP Elitebook 745 G4 AMD Pro A10 8730B 2.4GHz 8GB 128GB SSD 14.1" FHD Radeon 645',
 'New listingHP G56 15.6" Laptop Intel Dual Core T4500 Webcam 4GB RAM 500GB WIN 10 wifi DVD',
 'New listingDell Inspiron 5502 laptop 11th Gen Intel i5-1135G7, 16GB RAM, 256GB NVMe SSD',
 'Dell Latitude E7240 256GB HD 8GB RAM i7-4600 Win 10 Pro Laptop ( H272H ) USED',
 'Fast Dell HP Lenovo Laptop 14.1" Core i5 6th Gen 8GB Ram 240GB SSD Win 11 Wi-Fi',
 'New listingDell Laptop 7320 Windows 11 Pro i7 11th Gen 13.3 Inch 16GB RAM 256GB SSD',
 'Dell Latitude 5400 Touchscreen i7-8665U up to 64GB Ram up to 2TB SSD FHD Laptop',
 'ASUS Vivobook 15 OLED A1505ZA 15.6" Intel Core i5, 512 GB SSD - REFURB-B',
 'Budget Cheap Intel i5 8th Gen Laptop With Windows 10 8GB Memory 256GB SSD Wifi',
 'Geviar Laptop Computer, 15.6 Inch Laptop, 16GB DDR4 512GB SSD Intel Brand New',
 'SUPER FAST WINDOWS 10 CHEAP 15.6" LAPTOP INTEL CORE I3 16GB RAM 1TB HDD SSD CAM',
 "7'' Mini Laptop Computer Quad Core Android 12.0 Netbook 2GB RAM+32GB ROM For Kid",
 'Acer Nitro 5 Gaming Laptop AN515-58 Black #nb',
 'Lenovo Laptop ThinkPad P53S 15.6" i7-8565U 16GB 256GB SSD Windows 11 Pro',
 'New listingDell Laptop 7320 Windows 11 Pro i7 11th Gen 13.3 inch 16GB RAM 256GB SSD',
 'New listingLenovo ThinkPad  L13  13.3 " i5-10210U 1.6GHZ 8GB ,256GB SSD WIN 11 PRO ,SL1',
 'Acer ChromeBook CB3-111-C9K2 Intel Celeron 2.1 GHz 16GB SSD 2GB RAM Cheap Laptop',
 'CHEAP FAST Top Brand Windows 10/11 Laptop i3/i5/i7 32GB Ram 256GB / 1TB SSD WIFI',
 'New listingLENOVO THINKPAD T480s 14"  i5-8350U 1.7GHZ 16GB RAM 256GB SSD WIN 11 PRO ,SL9',
 'Windows 11 Laptop HP Dell HD screen Intel Core i3 i5 8GB 128GB SSD Warranty',
 'CHEAP Dell Latitude 3190 11.6" Laptop - Windows 11 Pro | Quad Core | Webcam',
 'New listingxps 13 7390 2-in-1 512GB 16GB memory',
 'Lenovo L14 Gen 1 AMD Ryzen 7 PRO 4750U 16GB DDR4 512GB SSD 14.0" Windows 11 Pro',
 'Gaming HP Omen  15.6" Intel core i5-8300H, 16GB Ram, 128GB SSD+1TB HDD, Wn11',
 'Panasonic Toughbook CF-20 Rugged Laptop Tablet  & Keyboard Win 10 Pro Up To 2 Tb',
 'Dell Vostro 14 5410 Intel Core i5-11320H 8GB DDR4 256GB SSD 14.0" Windows 11 Pro',
 'New listingHP ELITEBOOK 830 G6 WITH i5-8365U CPU 8GB RAM 256GB SSD WINDOWS 11',
 'New listingHP Elitebook 735 G5 Ryzen 5 Pro 2500U 2GHz 8GB 256GB SSD 13.3" FHD Radeon 715',
 'Dell Latitude 9520 Core i7 11th Gen 16gb  500gb SSD 15.6In FHD Dell warranty',
 'Lenovo ThinkPad L380 13.3" Laptop Intel Quad Core i5-8250U 8GB DDR4 256GB NVMe',
 'New listingGOLD LENOVO THINKPAD T480 LAPTOP CORE i5 8GB RAM 256GB SSD WINDOWS 11 FHD 14"',
 'Dell Latitude 7390 Core i5-8350U up to 64GB Ram up to 2TB SSD FHD Laptop',
 'Cheap Fast Dual Core Windows 10 Laptop 4GB 240GB WIFI',
 'New listingASUS Vivobook',
 'Lenovo ThinkPad T480 i5-8250U up to 64GB Ram up to 2TB SSD FHD Windows Laptop ~',
 'New listingLenovo ThinkPad L13 Core i5-10210U - 8GB RAM/256GB SSD FHD Windows 11 Pro Laptop',
 'GeoBook 1E N4020 4GB RAM 64GB SSD Win 10 Pro Ed ( Free Delivery )',
 'Lenovo ThinkPad X280 Laptop Intel Core i5 8th Gen 8GB RAM 256GB SSD Windows 11Charity item',
 'ASUS VivoBook X412 14" Full HD NanoEdge Laptop Core i3 8GB RAM 120GB SSD',
 'FAST WINDOWS 11 CHEAP LAPTOP INTEL CORE 8GB RAM 120 GB SSD WEBCAM WI-FI.',
 'Dell Laptop Latitude 7320 13.3" Windows 11 Intel Core i7 11th Gen 16GB RAM 256GB',
 "Portable 10.1'' Laptop Computer Quad Core Android 12.0 Netbook 2G RAM+64GB ROM",
 'New listingHP - HP ProBook 430 G5 - Core i5-8250U CPU @ 1.60GHz - 4GB - (128GB) SSD',
 'New listingToshiba Laptop NB305-N310 - 10" Screen - Intel Atom N450 1.66GHz',
 'New listingDell Latitude 3520 15.6" 256GB SSD, Intel i5 11th Gen., 2.40 GHz, 8GB. Black',
 'New listingLenovo IdeaPad - 1 14ADA05 - 14" (64GB eMMC, AMD Athlon 3020e, 1.20GHz, 4GB RAM)',
 'Lenovo Thinkpad T430 laptop 8GB 480Gb SSD Webcam DVD CD Windows 11 Pink Purple',
 'HP 255 G7 AMD Ryzen 3, 8GB RAM, 256GB SSD, DVD-RW Win10P 15.6" cheap Laptop',
 'Ms Office 2019 Professional Plus Lifetime Retail On USB Stick | Fast Post',
 'Panasonic Toughbook FZ-55 i5 MK3 16GB RAM 512GB SSD Win 11 Pro',
 'New listingDell Latitude 3420 14" i5-11TH GEN 4.2GHZ 8GB RAM 256GB NVME IRIS XE,WIN 11,,SL8',
 'New listingDell Latitude 5410 14" Laptop, Intel Core i5-10210U 1.60GHz, 16GB RAM, 256GB SSD',
 'HP ProBook 440 G6 intel i5-8250U 1.6Ghz 16GB RAM 512GB SSD FHD W11 GA',
 'SGIN Laptop 15.6" FHD Intel Celeron 2.50 GHz 8GB RAM 512GB SSD Windows 11 WiFi',
 'HP Elitebook 840 G7 Laptop Core i5 10210U 16GB RAM 512GB SSD Win 11 Renewed',
 'Dell Latitude Laptop Core i5-i7 8-13th Gen 8-32GB 256GB-1TB SSD Cheap Windows 11',
 'ASUS C223N  Intel Celeron N3350  4GB RAM 32GB 11.6 Chromebook - Grey',
 'New listingDell Latitude 7420 Laptop i7 11th Gen 3GHz 16GB 256GB 14" FHD Touch Win 11 Pro',
 'New listingFAST CHEAP Intel Core i3 / i5 LAPTOP - Windows 10 - WiFi - 4GB RAM - 120GB / 1TB',
 'Cheap Gaming Laptop Fast RYZEN 5 32GB RAM 1TB SSD 13.3 FHD Win11 Vega 8 GPU PC',
 'New listingLenovo ThinkPad T470 14" i5-7300U 8GB RAM 256GB SSD',
 'New listingTOSHIBA SATELLITE C55-c-184 NOTEBOOK/LAPTOP',
 'New listingLaptop Dell Latitude 7490 14-inch Core i5 8TH GEN 16GB RAM 256 SSD WINDOWS 11',
 'Dell Latitude 7320 i7-1165G7 2.80GHz 16GB 512GB SSD FHD Windows 11 Pro Laptop',
 'Blue Pink Lenovo ThinkPad T450 Core I5 8GB RAM 256GB SSD Windows 10 Pro Laptop',
 'New listingAcer Aspire 1640Z Vintage Win XP Retro Laptop Great Condition 2GB RAM 60GB HDD',
 'Laptop N5095 15.6 inch Netbooks PC Super Fast Ram 16 SSD 512G Windows 11 Pro New',
 'Cheap Laptop Mini Windows 10  Laptop 1.2Ghz 4GB RAM 64GB Storage',
 'New listingDell Latitude 5480 14" i5-7200U 2.5GHZ 16GB RAM 256GB SSD WIN 11 PRO ,SL15',
 'Dell Latitude 5280 12.5" i5-7200U | 16GB RAM | 512GB NVMe SSD | Windows 11',
 'New listinghp pavilion 15 laptop',
 'New listingVINTAGE Dell Windows 2000 Laptop with Parallel +Serial (RS232)Ports (D4)',
 'New listingDell Inspiron 1545 laptop for spares or repair',
 'Lenovo IdeaPad 3 15.6" Laptop (Intel Core i5-1155G7, 8GB RAM, 5126GB SSD, W11)',
 'New listingHP and ASUS laptop bundle Of 4 Laptops For Part Or Not Working',
 'Microsoft Surface Laptop 3 i5-1035G7 8GB 256GB Windows 11 Touchscreen Black 1868',
 'Acer Chromebook 514 CB514-1H Intel Pentium N4200 4GB RAM 32GB Storage ChromeOS',
 'Panasonic Toughbook CF19,i5 Rugged 8 Laptop  500 Gb Win 10 Or Win 7 Diagnostics.',
 'Dell Latitude 5300 Laptop, 13" Core i5 8th Gen, 8GB RAM, 256GB SSD, Windows 11',
 'FAST CHEAP CORE i3 i5 LAPTOP 8GB RAM 240GB SSD Wi-Fi Windows 10 HDMI Webcam WiFi',
 'FAST DELL E5470 CORE i5 14" HD 8GB RAM 128GB SSD WINDOWS 11 BUSINESS LAPTOP',
 'Samsung 300E  Core i5 3rd Generation.  8gb Ram With Charger.  Big Clearance',
 'Microsoft Surface Laptop Go Touchscreen i5 10th Gen 8GB RAM 256GB SSD Windows 11Charity item',
 'Microsoft Surface Laptop 4  i5-1145G7 8GB RAM 250GB Touchscreen Superb Condition',
 'Dell Latitude 5520 Intel Core i5-1145G7 16GB DDR4 256GB SSD 15.0" Windows 11 Pro',
 'Samsung Galaxy Book2 Go Laptop Snapdragon 7c+ Gen 3 4GB 128GB eMMC 14" FHD Win11',
 'Acer Aspire Vero Laptop AV15-53P Green #nb',
 'Lenovo 14 inch Chromebook N42-20 Laptop 4GB RAM 16GB eMMC Chrome OS HDMI WEBCAM',
 'Dell Latitude 5410 Windows 11 14" FHD Laptop Intel Core i5 10310U 8GB 256GB  SSD',
 'DELL Rugged 14 5430 i5 Quad Core 16GB 512GB SSD Win 11 Pro 1 YR Grade B',
 'Acer Chromebook 12" Spin 512 R851TN-P4VW 2in1 8GB-64GB Black A Grade Warranty',
 'Lenova Ideapad 110-151BR Laptop (UNTESTED)',
 'LENOVO X240 INTEL I3 WINDOWS 11 LAPTOP 12.5" HD 8GB RAM 128GB SSD WEBCAM HDMI',
 'New listingASUS TUF Gaming Laptop F15 I5 11th Gen, 16GB DDR4, RTX 3050 - Damaged',
 'New listingHP ZBook 17 G2 Laptop i7-4800MQ 16GB RAM 256GB SSD 1TB HDD NVIDIA QUADRO K4100M',
 'HP ProBook 430 G7 14" Laptop Intel Core i5-10210U 8GB 256 GB SSD Windows 10 Pro',
 'Lenovo ThinkPad T480 i7-8550U up to 64GB Ram up to 2TB SSD Windows 11 Laptop',
 'SUPER FAST WINDOWS 11 CHEAP LAPTOP INTEL CORE 16GB RAM 1TB SSD WEBCAM WI-FI',

In [10]:
len(product_names)

84

In [11]:
# PRICES EXTRACTION 
current_price =  []
prices = soup.find_all('span', class_='s-item__price' ) #CURRENT PRICE
for price in prices:
    current_price.append(price.get_text(strip=True))
len(current_price)

87

In [12]:
current_price

['$20.00',
 '$20.00',
 '£189.99to£420.00',
 '£129.99to£299.99',
 '£129.99to£254.99',
 '£94.99to£134.99',
 '£99.99to£219.99',
 '£35.99',
 '£89.99',
 '£29.98',
 '£199.99',
 '£149.99',
 '£219.99',
 '£309.99',
 '£86.99',
 '£144.95',
 '£248.99',
 '£159.99',
 '£74.99',
 '£49.99',
 '£119.99',
 '£29.95',
 '£109.99to£329.99',
 '£209.99',
 '£99.99to£119.99',
 '£99.99',
 '£54.99',
 '£67.96to£84.96',
 '£79.00',
 '£219.99to£504.99',
 '£134.99',
 '£119.99to£169.99',
 '£139.00to£234.00',
 '£14.99',
 '£52.71',
 '£104.72',
 '£363.72',
 '£69.99',
 '£63.12',
 '£219.00',
 '£151.10',
 '£109.99',
 '£229.00',
 '£159.99to£489.99',
 '£9.99',
 '£71.99to£79.99',
 '£130.61',
 '£120.31',
 '£49.99',
 '£118.99',
 '£199.99to£589.99',
 '£229.99',
 '£70.00',
 '£99.52',
 '£99.52',
 '£120.00',
 '£104.72',
 '£65.00',
 '£73.52',
 '£69.95to£89.95',
 '£63.12',
 '£144.76',
 '£129.99',
 '£98.01',
 '£89.95to£279.95',
 '£59.99',
 '£104.72',
 '£144.95',
 '£70.00',
 '£249.99to£534.99',
 '£159.00',
 '£125.99',
 '£73.52',
 '£30.00',
 '£109.99',
 '£47.52',
 '£49.60',
 '£134.95',
 '£245.00',
 '£310.64',
 '£37.12',
 '£249.99to£534.99',
 '£159.00',
 '£59.95to£102.95',
 '£40.00',
 '£139.99',
 '£899.99']

In [13]:
len(product_names), len(current_price)

(84, 87)

In [14]:
# FORMER PRICE
former_price = [] 

prices = soup.find_all('span', class_='STRIKETHROUGH' ) #FORMER PRICE
for price in prices:
    former_price.append(price.get_text(strip= True))

In [15]:
former_price

['£849.95',
 '£749.95',
 '£59.99',
 '£399.95',
 '£849.95',
 '£258.99',
 '£79.95',
 '£439.99',
 '£400.00',
 '£799.95',
 '£99.99',
 '£449.99',
 '£649.99',
 '£999.99']

In [16]:
len(product_names), len(current_price) ,len(former_price)

(84, 87, 14)

In [17]:
# ITEMS SOLD
all_items_solds = [] 

items = soup.find_all('span', class_="s-item__dynamic s-item__quantitySold" ) #ITEMS SOLD
for item in items:
    all_items_solds.append(item.get_text(strip= True))

In [18]:
len(product_names), len(current_price) ,len(former_price), len(all_items_solds)

(84, 87, 14, 27)

In [19]:
all_items_solds

['9+ sold',
 '103+ sold',
 '562 sold',
 '954 sold',
 '21+ sold',
 '210+ sold',
 '548+ sold',
 '126 sold',
 '12+ sold',
 '254+ sold',
 '132 sold',
 '14 sold',
 '525 sold',
 '224 sold',
 '548+ sold',
 '14 sold',
 '41+ sold',
 '56 sold',
 '32 sold',
 '949 sold',
 '31 sold',
 '50 sold',
 '254+ sold',
 '31 sold',
 '18 sold',
 '131 sold',
 '69 sold']

In [20]:
# SELLER INFO
all_seller_info = [] 

items_seller = soup.find_all('span', class_="s-item__seller-info-text" ) #SELLER INFO 
for items in items_seller:
    all_seller_info.append(items.get_text(strip= True))

In [21]:
all_seller_info

['birmingham-av (12,057) 98.8%',
 'birmingham-av (12,057) 98.8%',
 'good-cheap-laptops (9,794) 97.1%',
 'giga-refurb (8,503) 98.4%',
 'gadgetsxpress7 (4,550) 99.7%',
 'mobstars (23,014) 98.9%',
 'birmingham-av (12,057) 98.8%',
 'kel-tel (30,178) 99.4%',
 'birmingham-av (12,057) 98.8%',
 'birmingham-av (12,057) 98.8%',
 'newandusedlaptops4u (77,525) 99.6%',
 'newandusedlaptops4u (77,525) 99.6%',
 'resycit (6,563) 99.3%',
 'venoscorp (19,963) 98.4%',
 'meshshop (4,286) 100%',
 'giga-refurb (8,503) 98.4%',
 'quattro_outlet (29) 100%',
 'talostrades (0) 0%',
 'ecolaptop (14,365) 99.4%',
 'pcs4u-uk (2,556) 99.5%',
 'birmingham-av (12,057) 98.8%',
 'newandusedlaptops4u (77,525) 99.6%',
 'giga-refurb (8,503) 98.4%',
 'recycly.tech (2,341) 98.3%',
 'yellowape (5,270) 98.8%',
 'priceholes-com (9,325) 99.6%',
 'orioncomputersuk (750) 99.6%',
 'newandusedlaptops4u (77,525) 99.6%',
 'laptop-top-deals (8,125) 99.3%',
 'giga-refurb (8,503) 98.4%',
 'venoscorp (19,963) 98.4%',
 'comm-2648 (9,815) 99.8%',
 'state_of_mind1 (493) 100%',
 'mathunt-4514 (11) 100%',
 'orioncomputersuk (750) 99.6%',
 'sebrab73 (23) 100%',
 'hpstoreuk (28,989) 99.1%',
 'us0002x96 (238) 98.4%',
 'recycly.tech (2,341) 98.3%',
 'us0002x96 (238) 98.4%',
 'birmingham-av (12,057) 98.8%',
 'st-elizabeth-hospice (27,590) 99.8%',
 'ri-services (31,554) 95.3%',
 'moobash (2) 100%',
 'kesta_5407 (0) 0%',
 'surfurb (629) 100%',
 'recycly.tech (2,341) 98.3%',
 'toughbook-outlet (12,188) 99.8%',
 'rapid-it-ltd (25,000) 100%',
 'talostrades (0) 0%',
 'daar.uk.ui2m7s (77) 98.4%',
 'thomacudmo (315) 100%',
 'hanoversolutionsltd (1,045) 100%',
 'sto-421214 (70) 100%',
 'airedalecomputers (3,922) 99.3%',
 'peacockdm (349) 100%',
 'priceholes-com (9,325) 99.6%',
 'shauk87 (180) 100%',
 'gamacd9247 (1) 100%',
 'itmonster (885) 99.5%',
 'ukfobs (3,004) 100%',
 'blackhawk-gaming-uk (5,353) 100%',
 'orioncomputersuk (750) 99.6%',
 'pc_bits_and_bobs (58) 100%',
 'venoscorp (19,963) 98.4%',
 'react_sales (507) 100%',
 'newandusedlaptops4u (77,525) 99.6%',
 'high-tec (796) 100%',
 'innofinity-worldwide (132,456) 98.4%',
 'sylarius78 (2,264) 100%',
 'omegatechsyst (1,209) 100%',
 'itmonster (885) 99.5%',
 'willerby_6137 (1,204) 100%',
 'jamesk1982 (844) 100%',
 'manda*h (2,825) 99.6%',
 'us0002x96 (238) 98.4%',
 'thinkpadmike-com (1,491) 97.4%',
 'richwatches2023 (86) 100%',
 'newandusedlaptops4u (77,525) 99.6%',
 'noble_cruncher_shop (1,985) 99.2%',
 'priceholes-com (9,325) 99.6%',
 'comm-2648 (9,815) 99.8%',
 'giga-refurb (8,503) 98.4%',
 'acer_store_uk (172) 100%']

In [22]:
# BRAND CATEGORY
brand_category = [] 

brands= soup.find_all('span', class_="SECONDARY_INFO" ) # BRANDS
for brand in brands:
    brand_category.append(brand.get_text(strip= True))

In [23]:
len(product_names), len(current_price) ,len(former_price), len(all_items_solds), len(all_seller_info), len(brand_category)

(84, 87, 14, 27, 84, 78)

In [45]:
brand_category

['Brand New',
 'Brand New',
 'Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Excellent - Refurbished',
 'Brand new',
 'Brand new',
 'Brand new',
 'Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Opened – never used',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Parts only',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand new',
 'Brand New',
 'Brand New',
 'Brand new',
 'Brand new',
 'Parts only',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Excellent - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Brand new',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Good - Refurbished',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Opened – never used',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Brand new',
 'Brand New',
 'Brand New',
 'Good - Refurbished',
 'Brand new',
 'Brand new',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Brand new',
 'Excellent - Refurbished',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Brand new',
 'Parts only',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Excellent - Refurbished',
 'Good - Refurbished',
 'Brand New',
 'Brand New',
 'Brand new',
 'Very Good - Refurbished',
 'Pre-owned',
 'Opened – never used',
 'Very Good - Refurbished',
 'Parts only',
 'Very Good - Refurbished',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Excellent - Refurbished',
 'Pre-owned',
 'Brand new',
 'Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Excellent - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Good - Refurbished',
 'Brand New',
 'Brand New',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Brand new',
 'Pre-owned',
 'Good - Refurbished',
 'Opened – never used',
 'Brand new',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Good - Refurbished',
 'Brand new',
 'Brand new',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Certified - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Brand new',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand New',
 'Brand New',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Good - Refurbished',
 'Brand new',
 'Brand new',
 'Brand new',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Good - Refurbished',
 'Brand new',
 'Parts only',
 'Very Good - Refurbished',
 'Pre-owned',
 'Brand new',
 'Very Good - Refurbished',
 'Excellent - Refurbished',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Good - Refurbished',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Brand new',
 'Excellent - Refurbished',
 'Brand New',
 'Brand New',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Excellent - Refurbished',
 'Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Excellent - Refurbished',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Certified - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Brand New',
 'Brand New',
 'Brand new',
 'Good - Refurbished',
 'Brand new',
 'Brand new',
 'Opened – never used',
 'Good - Refurbished',
 'Certified - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Good - Refurbished',
 'Brand new',
 'Very Good - Refurbished',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand new',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Opened – never used',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Opened – never used',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Opened – never used',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Excellent - Refurbished',
 'Very Good - Refurbished',
 'Brand New',
 'Brand New',
 'Brand new',
 'Brand new',
 'Good - Refurbished',
 'Good - Refurbished',
 'Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Excellent - Refurbished',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Opened – never used',
 'Good - Refurbished',
 'Opened – never used',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Certified - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Brand New',
 'Brand New',
 'Opened – never used',
 'Very Good - Refurbished',
 'Brand new',
 'Very Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Opened – never used',
 'Very Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Opened – never used',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Opened – never used',
 'Pre-owned',
 'Parts only',
 'Very Good - Refurbished',
 'Brand new',
 'Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Parts only',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Pre-owned',
 'Good - Refurbished',
 'Brand new',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Brand New',
 'Brand New',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Brand new',
 'Brand new',
 'Parts only',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Opened – never used',
 'Pre-owned',
 'Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand new',
 'Brand new',
 'Pre-owned',
 'Brand new',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Excellent - Refurbished',
 'Brand new',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Brand new',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Excellent - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Brand New',
 'Brand New',
 'Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Brand new',
 'Good - Refurbished',
 'Excellent - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Parts only',
 'Parts only',
 'Parts only',
 'Pre-owned',
 'Brand new',
 'Very Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Opened – never used',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Parts only',
 'Very Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Parts only',
 'Very Good - Refurbished',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Very Good - Refurbished',
 'Opened – never used',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Opened – never used',
 'Pre-owned',
 'Pre-owned',
 'Good - Refurbished',
 'Good - Refurbished',
 'Opened – never used',
 'Very Good - Refurbished',
 'Pre-owned',
 'Good - Refurbished',
 'Brand New',
 'Brand New',
 'Brand new',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Very Good - Refurbished',
 'Opened – never used',
 'Very Good - Refurbished',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Parts only',
 'Brand new',
 'Opened – never used',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Brand new',
 'Very Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Opened – never used',
 'Parts only',
 'Pre-owned',
 'Brand new',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Opened – never used',
 'Good - Refurbished',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Excellent - Refurbished',
 'Parts only',
 'Pre-owned',
 'Good - Refurbished',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Opened – never used',
 'Pre-owned',
 'Pre-owned',
 'Brand new',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Pre-owned',
 'Parts only',
 'Pre-owned',
 'Very Good - Refurbished',
 'Good - Refurbished',
 ...]

In [25]:
len(product_names), len(current_price) ,len(former_price), len(all_items_solds), len(brand_category)

(84, 87, 14, 27, 78)

In [26]:
data = {
    'title' : product_names,
    'current_price' : current_price,
    'former_price' : former_price,
    'all_items_solds' : all_items_solds,
    'brand_category': brand_category,
    'all_seller_info' : all_seller_info
}

laptop_df = pd.DataFrame.from_dict(data, orient= 'index')

In [43]:
laptop_df.head()

,0,1,2,3,4,5,6,7,8,9,...,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510
title,Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN ...,FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WAR...,FAST CHEAP TOP BRAND INTEL CORE i5 8TH GEN 16G...,CUSTOM FAST CHEAP LAPTOP Intel Core i3/i5 - Wi...,SUPER FAST WINDOWS 11 CHEAP LAPTOP INTEL CORE ...,Lenovo MIIX 320-10ICR 2in1 tablet - Intel Atom...,CHEAP FAST Laptop DELL Quad Core 2.6GHZ Window...,"Stone StoneBook Mini M10A 11.6"" Laptop 120GB S...",Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN ...,FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WAR...,...,None,None,None,None,None,None,None,None,None,None
current_price,$20.00,$20.00,£189.99to£420.00,£129.99to£299.99,£129.99to£254.99,£94.99to£134.99,£99.99to£219.99,£35.99,£89.99,£29.98,...,£83.91,£8.99,£16.99,£82.88,£9.99,£669.71,£28.99,£179.00,£477.00,£389.00
former_price,£849.95,£749.95,£59.99,£399.95,£849.95,£258.99,£79.95,£439.99,£400.00,£799.95,...,None,None,None,None,None,None,None,None,None,None
all_items_solds,9+ sold,103+ sold,562 sold,954 sold,21+ sold,210+ sold,548+ sold,126 sold,12+ sold,254+ sold,...,None,None,None,None,None,None,None,None,None,None
brand_category,Brand New,Brand New,Good - Refurbished,Good - Refurbished,Very Good - Refurbished,Very Good - Refurbished,Good - Refurbished,Very Good - Refurbished,Good - Refurbished,Pre-owned,...,None,None,None,None,None,None,None,None,None,None

In [39]:
laptop_df = laptop_df.transpose()
laptop_df.head()

,0,1,2,3,4,5,6,7,8,9,...,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510
title,Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN ...,FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WAR...,FAST CHEAP TOP BRAND INTEL CORE i5 8TH GEN 16G...,CUSTOM FAST CHEAP LAPTOP Intel Core i3/i5 - Wi...,SUPER FAST WINDOWS 11 CHEAP LAPTOP INTEL CORE ...,Lenovo MIIX 320-10ICR 2in1 tablet - Intel Atom...,CHEAP FAST Laptop DELL Quad Core 2.6GHZ Window...,"Stone StoneBook Mini M10A 11.6"" Laptop 120GB S...",Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN ...,FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WAR...,...,None,None,None,None,None,None,None,None,None,None
current_price,$20.00,$20.00,£189.99to£420.00,£129.99to£299.99,£129.99to£254.99,£94.99to£134.99,£99.99to£219.99,£35.99,£89.99,£29.98,...,£83.91,£8.99,£16.99,£82.88,£9.99,£669.71,£28.99,£179.00,£477.00,£389.00
former_price,£849.95,£749.95,£59.99,£399.95,£849.95,£258.99,£79.95,£439.99,£400.00,£799.95,...,None,None,None,None,None,None,None,None,None,None
all_items_solds,9+ sold,103+ sold,562 sold,954 sold,21+ sold,210+ sold,548+ sold,126 sold,12+ sold,254+ sold,...,None,None,None,None,None,None,None,None,None,None
brand_category,Brand New,Brand New,Good - Refurbished,Good - Refurbished,Very Good - Refurbished,Very Good - Refurbished,Good - Refurbished,Very Good - Refurbished,Good - Refurbished,Pre-owned,...,None,None,None,None,None,None,None,None,None,None

In [46]:
# FOR ALL PAGES
pages = [x for x in range(1, 20)]

product_names = []
current_price =  []
former_price = []
all_items_solds = [] 
all_seller_info = [] 
brand_category = [] 

for page in pages:
    url = f'https://www.ebay.co.uk/sch/i.html?_nkw=laptops&_sacat=0&_from=R40&_ipg=60&rt=nc&_pgn={page}'
    response = requests.get(url)

    soup = BeautifulSoup(response.text, 'lxml')
    
    # PRODUCT NAMES
    names = soup.find_all('span', role='heading' ) # PRODUCT NAME
    for name in names[2:]:
        product_names.append(name.get_text(strip=True))
    
    # PRICES EXTRACTION 
    prices = soup.find_all('span', class_='s-item__price' ) #CURRENT PRICE
    for price in prices:
        current_price.append(price.get_text(strip=True))

    # FORMER PRICE
    prices = soup.find_all('span', class_='STRIKETHROUGH' ) #FORMER PRICE
    for price in prices:
        former_price.append(price.get_text(strip= True))
    
    # ITEMS SOLD
    items = soup.find_all('span', class_="s-item__dynamic s-item__quantitySold" ) #ITEMS SOLD
    for item in items:
        all_items_solds.append(item.get_text(strip= True))
    
    # BRAND CATEGORY
    brands= soup.find_all('span', class_="SECONDARY_INFO" ) #ITEMS SOLD
    for brand in brands:
        brand_category.append(brand.get_text(strip= True))
    
    # SELLER INFO
    items_seller = soup.find_all('span', class_="s-item__seller-info-text" ) #SELLER INFO
    for items in items_seller:
        all_seller_info.append(items.get_text(strip= True))
    
data = {
'title' : product_names,
'current_price' : current_price,
'former_price' : former_price,
'all_items_solds' : all_items_solds,
'brand_category': brand_category,
'all_seller_info' : all_seller_info
}

laptop_df = pd.DataFrame.from_dict(data, orient= 'index')
laptop_df = laptop_df.transpose()
laptop_df.head()

,title,current_price,former_price,all_items_solds,brand_category,all_seller_info
0,FAST CHEAP TOP BRAND INTEL CORE i5 8TH GEN 16G...,$20.00,"£1,049.95",171+ sold,Brand New,"good-cheap-laptops (9,794) 97.1%"
1,Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN ...,$20.00,£649.95,30+ sold,Brand New,"birmingham-av (12,057) 98.8%"
2,FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WAR...,£129.99to£254.99,£439.99,548+ sold,Very Good - Refurbished,"birmingham-av (12,057) 98.8%"
3,Lenovo ThinkPad T480 i5-8250U up to 64GB Ram u...,£189.99to£420.00,£399.95,103+ sold,Good - Refurbished,"newandusedlaptops4u (77,525) 99.6%"
4,SUPER FAST WINDOWS 11 CHEAP LAPTOP INTEL CORE ...,£129.99to£299.99,£59.99,954 sold,Good - Refurbished,"gadgetsxpress7 (4,550) 99.7%"

In [30]:
laptop_df.to_csv('Laptop Record.csv', index=False)

 Data Transformation

In [31]:
# COPY DATA TO KEEP THE RAW DATA
df = laptop_df.copy()

In [32]:
# CHECKING THE DATA INFO
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1452 non-null   object
 1   current_price    1511 non-null   object
 2   former_price     244 non-null    object
 3   all_items_solds  202 non-null    object
 4   brand_category   1482 non-null   object
 5   all_seller_info  1452 non-null   object
dtypes: object(6)
memory usage: 71.0+ KB

In [33]:
df.fillna({
    'title' : 'Unknown',
    'former_price': 0.0,
    'all_items_solds' : 'Unknown',
    'brand_category' : 'Unknown',
    'all_seller_info' : 'Unknown'
}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            1511 non-null   object
 1   current_price    1511 non-null   object
 2   former_price     1511 non-null   object
 3   all_items_solds  1511 non-null   object
 4   brand_category   1511 non-null   object
 5   all_seller_info  1511 non-null   object
dtypes: object(6)
memory usage: 71.0+ KB

In [47]:
df.head()

,title,current_price,former_price,all_items_solds,brand_category,all_seller_info
0,Laptop HP Windows 11 CORE i5 GEN 6 - 12TH GEN ...,$20.00,£849.95,9+ sold,Brand New,"birmingham-av (12,057) 98.8%"
1,FAST CHEAP CORE i5 LAPTOP 1TB SSD 32GB RAM WAR...,$20.00,£749.95,103+ sold,Brand New,"birmingham-av (12,057) 98.8%"
2,FAST CHEAP TOP BRAND INTEL CORE i5 8TH GEN 16G...,£189.99to£420.00,£59.99,562 sold,Good - Refurbished,"good-cheap-laptops (9,794) 97.1%"
3,CUSTOM FAST CHEAP LAPTOP Intel Core i3/i5 - Wi...,£129.99to£299.99,£399.95,954 sold,Good - Refurbished,"giga-refurb (8,503) 98.4%"
4,SUPER FAST WINDOWS 11 CHEAP LAPTOP INTEL CORE ...,£129.99to£254.99,£849.95,21+ sold,Very Good - Refurbished,"gadgetsxpress7 (4,550) 99.7%"

LOADING DATA TO DATABASE

In [35]:
# ACCESSING THE DATABASE
load_dotenv(override=True)
db_user = os.getenv('DB_USER')
db_name = os.getenv('DB_NAME')
db_host = os.getenv('DB_HOST')
db_port = os.getenv('DB_PORT')
db_password = os.getenv('DB_PASSWORD')

In [36]:
db_name

'JUNO_ECOMMERCE'

In [37]:
database_url = f"postgresql+psycopg2://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
engine = create_engine(database_url)
display('Connected successfully')

'Connected successfully'

In [38]:
laptop_records = df.copy()
laptop_records.to_sql('Laptop_Records',engine, if_exists='replace', index=False)

511